// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaccApp.Models;

namespace VaccApp.Migrations
{
    [DbContext(typeof(VaccContext))]
    [Migration("20210929153607_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VaccApp.Models.Ambulanta", b =>
                {
                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Adresa");

                    b.Property<int?>("GradID")
                        .HasColumnType("int");

                    b.Property<int>("PreostalaMestaZaVakcinaciju")
                        .HasColumnType("int")
                        .HasColumnName("PreostalaMesta");

                    b.HasKey("Adresa");

                    b.HasIndex("GradID");

                    b.ToTable("Ambulante");
                });

            modelBuilder.Entity("VaccApp.Models.Grad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("VaccApp.Models.Gradjanin", b =>
                {
                    b.Property<long>("JMBG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("JMBG")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ime");

                    b.Property<string>("IzabranaAmbulantaAdresa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("IzabranaVakcinaID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Prezime");

                    b.HasKey("JMBG");

                    b.HasIndex("IzabranaAmbulantaAdresa");

                    b.HasIndex("IzabranaVakcinaID");

                    b.ToTable("Gradjani");
                });

            modelBuilder.Entity("VaccApp.Models.Vakcina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AmbulantaAdresa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.HasIndex("AmbulantaAdresa");

                    b.ToTable("Vakcine");
                });

            modelBuilder.Entity("VaccApp.Models.Ambulanta", b =>
                {
                    b.HasOne("VaccApp.Models.Grad", null)
                        .WithMany("Ambulante")
                        .HasForeignKey("GradID");
                });

            modelBuilder.Entity("VaccApp.Models.Gradjanin", b =>
                {
                    b.HasOne("VaccApp.Models.Ambulanta", "IzabranaAmbulanta")
                        .WithMany()
                        .HasForeignKey("IzabranaAmbulantaAdresa");

                    b.HasOne("VaccApp.Models.Vakcina", "IzabranaVakcina")
                        .WithMany()
                        .HasForeignKey("IzabranaVakcinaID");

                    b.Navigation("IzabranaAmbulanta");

                    b.Navigation("IzabranaVakcina");
                });

            modelBuilder.Entity("VaccApp.Models.Vakcina", b =>
                {
                    b.HasOne("VaccApp.Models.Ambulanta", null)
                        .WithMany("DostupneVakcine")
                        .HasForeignKey("AmbulantaAdresa");
                });

            modelBuilder.Entity("VaccApp.Models.Ambulanta", b =>
                {
                    b.Navigation("DostupneVakcine");
                });

            modelBuilder.Entity("VaccApp.Models.Grad", b =>
                {
                    b.Navigation("Ambulante");
                });
#pragma warning restore 612, 618
        }
    }
}
